### ISSUE TITLE
Setting channel names

### ISSUE THREAD

**Issue by JacobHast** [qua-platform/quam#50]
Would it be possible to add support for manually setting the name attribute of a Channel? The default could be a reference to the current name property, but in some cases I would like to overwrite this name and set a name manually

**Comment by nulinspiratie** [comment]
Have a look at the parameter I'd, it sounds like it implements what you need, let me know if it works

**Comment by JacobHast** [comment]
Ahh yes, this was what I needed

**Comment by nulinspiratie** [comment]
Closing issue, @JacobHast please reopen if unresolved
