### ISSUE TITLE
Multiple integration weight sets 

### ISSUE THREAD

**Issue by JacobHast** [qua-platform/quam#55]
Is it possible to have multiple sets of integration weights for a ReadoutPulse? E.g. I might want to compare readout using simple flat weights with optimally shaped weights.

**Comment by nulinspiratie** [comment]
Hey Jacob, we decided in QuAM to keep one set of integration weights per pulse, and therefore identical pulses with different integration weights should be defined as separate pulses

**Comment by JacobHast** [comment]
Ahh, I see, we try that then!

**Comment by nulinspiratie** [comment]
Closing issue, @JacobHast please reopen if not resolved
