### ISSUE TITLE
Every second Octave RF output should have external LO source

### ISSUE THREAD

**Issue by nulinspiratie** [qua-platform/quam#66]

**Comment by MichalGQM** [comment]
Hello,
Regarding the default internal source of the octave: 
* RF outputs 1-5 - the default to all of them should be internal
* RF input 1 - the default should be internal
* RF input 2 - the default should be internal
All of them should also have the other option ("external"/"internal") as well.

**Comment by nulinspiratie** [comment]
Fixed in #69
