### ISSUE TITLE
Setting referenced values

### ISSUE THREAD

**Issue by JacobHast** [qua-platform/quam#85]
When using quam, we found that we often need to change values that are references, and doing so generally instantiates a "treasure-hunt", following references in our machine until the "bare" value is found. In practice, doing this can become a bit tedious - would it be possible to add a method QuamComponent, e.g. `.set_at_reference(attr: str, new_value)`  which follows the references for you and sets it at the correct place? 

And for added user-clarity, maybe this function could even search the machine from the "bare" value, to see if other components reference this value, and correspondingly print out exactly which components were affected by the change?

**Comment by nulinspiratie** [comment]
I like it! I created a PR introducing this functionality.
The second part about searching the machine for other attributes that are a reference to the updated value is a tricky one as it's not always apparent when something is referencing a given attribute. I'll leave this as a follow-up feature.

**Comment by JacobHast** [comment]
Amazing, thanks!
