### ISSUE TITLE
Irrelevant UserWarning with default root references 

### ISSUE THREAD

**Issue by JacobHast** [qua-platform/quam#92]
If I make a QuamRoot with one component referencing another, I get a UserWarning, even though everything otherwise seems to work properly, as illustrated in the below example:

```
from quam import QuamRoot, QuamComponent, quam_dataclass

@quam_dataclass
class Component(QuamComponent):
    y: int = 2

@quam_dataclass
class Root(QuamRoot):
    a: Component
    b: Component = "#/a"

root = Root(a=Component())
```

I get:
`UserWarning: No QuamRoot initialized, cannot retrieve reference #/a from Root
`

**Comment by nulinspiratie** [comment]
Good catch, created a PR
